name: SubtleRPG
main: cc.isotopestudio.SubtleRPG.subtlerpg.SubtleRPG
author: Mars
website: http://isotopestudio.cc
version: 1.2
commands:
  SubtleRPG:
    description: SubtleRPG Command.
    usage: /SubtleRPG help