Health:
  #血条长度，10为5颗心
  Scale: 10

#默认职业的属性
DefaultGroup:
  Health:
    default: 20.0
    levPeriod: 1
    increasePerPeriod: 0.0
    max: 20.0
  Attack:
    default: 0.0
    levPeriod: 1
    increasePerPeriod: 0.0
    max: 0.0
  Defence:
    default: 0.0
    levPeriod: 1
    increasePerPeriod: 1.0
    max: 20.0

#职业列表
#需要与groups.yml里的一致
Groups:
  - hunter
  - archer

#关于权限
#  - subtleRPG.<groups中的名字>
#如:
#  - subtleRPG.hunter
#  - subtleRPG.archer